### ISSUE TITLE
[docs]: Suggestion for better motto.

### ISSUE THREAD

**Issue by Rudra-Ji** [enrich-platforms/toppings-web#2]
## Issue Type
- [x] Other (Specify)

## Description
The motto you are currently using could be better framed to express your vision in a more pleasing way,  I have a better suggestion for the same which suits your vision.

## Expected Behavior
I suggest this `We work hard, so you don't have to.`

## Current Behavior
The current motto is `We are on a mission to make your life easier.`

**Comment by DarhkVoyd** [comment]
Hi @Rudra-Ji,

Thank you for your suggestion! We appreciate your input. Your proposed motto does resonate with our vision. I've assigned this issue to you, and you can go ahead and work on it. If you have any further ideas or suggestions, feel free to share them as well.
